version: '3'
services:
  postgres_test:
    image: library/postgres:12.3-alpine
    ports:
      - ${POSTGRES_ADDRESS:-127.0.0.1:5434}:5432
    environment:
      - POSTGRES_PASSWORD=servientrega_test
      - POSTGRES_USER=servientrega_test
      - POSTGRES_DB=servientrega_test
  node:
    environment:
      - NODE_ENV=development
