version: '3'
services:
  postgres_test:
    image: library/postgres:12-alpine
    ports:
      - ${DB_TEST_CONTAINER_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=servientrega_test
      - POSTGRES_USER=servientrega_test
      - POSTGRES_DB=servientrega_test
  node:
    environment:
      - NODE_ENV=development
