version: '3'
services:
  app:
    entrypoint: make run
    user: ${UID:-1000}:${GID:-1000}
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/servientrega
      - ./.docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: library/postgres:12-alpine
    ports:
      - ${POSTGRES_ADDRESS:-127.0.0.1:5432}:5432
    environment:
      - POSTGRES_PASSWORD=servientrega
      - POSTGRES_USER=servientrega
      - POSTGRES_DB=servientrega
  node:
    command: make watch
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - NODE_ENV=dev
