version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - ./:/var/www/servientrega
    environment:
     - COMPOSER_HOME=/tmp
    working_dir: /var/www/servientrega
  node:
    image: "library/node:lts"
    volumes:
      - ./:/var/www/servientrega
    working_dir: /var/www/servientrega
    environment:
      - NODE_ENV=dev
      - HOME=/var/www/servientrega
      - NODE_OPTIONS=--openssl-legacy-provider
