<?php

namespace App\Servientrega;

use App\Servientrega\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class ServientregaClassmap
{
    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('DesencriptarContrasena', Type\DesencriptarContrasena::class),
            new ClassMap('DesencriptarContrasenaResponse', Type\DesencriptarContrasenaResponse::class),
            new ClassMap('EncriptarContrasena', Type\EncriptarContrasena::class),
            new ClassMap('EncriptarContrasenaResponse', Type\EncriptarContrasenaResponse::class),
            new ClassMap('CargueMasivoExterno', Type\CargueMasivoExterno::class),
            new ClassMap('ArrayOfCargueMasivoExternoDTO', Type\ArrayOfCargueMasivoExternoDTO::class),
            new ClassMap('CargueMasivoExternoDTO', Type\CargueMasivoExternoDTO::class),
            new ClassMap('ArrayOfEnviosExterno', Type\ArrayOfEnviosExterno::class),
            new ClassMap('EnviosExterno', Type\EnviosExterno::class),
            new ClassMap('ArrayOfEnviosUnidadEmpaqueCargue', Type\ArrayOfEnviosUnidadEmpaqueCargue::class),
            new ClassMap('EnviosUnidadEmpaqueCargue', Type\EnviosUnidadEmpaqueCargue::class),
            new ClassMap('ArrayOfString', Type\ArrayOfString::class),
            new ClassMap('CargueMasivoExternoResponse', Type\CargueMasivoExternoResponse::class),
            new ClassMap('AuthHeader', Type\AuthHeader::class),
            new ClassMap('CargueMasivoExternoDetalle', Type\CargueMasivoExternoDetalle::class),
            new ClassMap('ArrayOfCargueMasivoExternoDetalleDTO', Type\ArrayOfCargueMasivoExternoDetalleDTO::class),
            new ClassMap('CargueMasivoExternoDetalleDTO', Type\CargueMasivoExternoDetalleDTO::class),
            new ClassMap('ArrayOfEnviosExternoDetalle', Type\ArrayOfEnviosExternoDetalle::class),
            new ClassMap('EnviosExternoDetalle', Type\EnviosExternoDetalle::class),
            new ClassMap('ArrayOfEnviosUnidadEmpaqueCargueDetalle', Type\ArrayOfEnviosUnidadEmpaqueCargueDetalle::class),
            new ClassMap('EnviosUnidadEmpaqueCargueDetalle', Type\EnviosUnidadEmpaqueCargueDetalle::class),
            new ClassMap('CargueMasivoExternoDetalleResponse', Type\CargueMasivoExternoDetalleResponse::class),
            new ClassMap('GenerarGuiaSticker', Type\GenerarGuiaSticker::class),
            new ClassMap('GenerarGuiaStickerResponse', Type\GenerarGuiaStickerResponse::class),
            new ClassMap('GenerarGuiaStickerMobile', Type\GenerarGuiaStickerMobile::class),
            new ClassMap('GenerarGuiaStickerMobileResponse', Type\GenerarGuiaStickerMobileResponse::class),
            new ClassMap('GenerarGuiaStickerTiendasVirtuales', Type\GenerarGuiaStickerTiendasVirtuales::class),
            new ClassMap('GenerarGuiaStickerTiendasVirtualesResponse', Type\GenerarGuiaStickerTiendasVirtualesResponse::class),
            new ClassMap('ConsultarUnidadEmpaqueIdLogin', Type\ConsultarUnidadEmpaqueIdLogin::class),
            new ClassMap('ConsultarUnidadEmpaqueIdLoginResponse', Type\ConsultarUnidadEmpaqueIdLoginResponse::class),
            new ClassMap('ConsultarUnidadEmpaqueIdLoginResult', Type\ConsultarUnidadEmpaqueIdLoginResult::class),
            new ClassMap('ConsultarRestriccionesFisicasEnvios', Type\ConsultarRestriccionesFisicasEnvios::class),
            new ClassMap('ConsultarRestriccionesFisicasEnviosResponse', Type\ConsultarRestriccionesFisicasEnviosResponse::class),
            new ClassMap('ConsultarRestriccionesFisicasEnviosResult', Type\ConsultarRestriccionesFisicasEnviosResult::class),
            new ClassMap('ConsultarGuiasByNumDocumento', Type\ConsultarGuiasByNumDocumento::class),
            new ClassMap('ConsultarGuiasByNumDocumentoResponse', Type\ConsultarGuiasByNumDocumentoResponse::class),
            new ClassMap('ConsultarGuiasByNumDocumentoResult', Type\ConsultarGuiasByNumDocumentoResult::class),
            new ClassMap('InsertarSertEnvio', Type\InsertarSertEnvio::class),
            new ClassMap('documento', Type\Documento::class),
            new ClassMap('InsertarSertEnvioResponse', Type\InsertarSertEnvioResponse::class),
            new ClassMap('ActualizarSertEnvio', Type\ActualizarSertEnvio::class),
            new ClassMap('ActualizarSertEnvioResponse', Type\ActualizarSertEnvioResponse::class),
            new ClassMap('ActualizarEnvioAgregarUnidades', Type\ActualizarEnvioAgregarUnidades::class),
            new ClassMap('ActualizarEnvioAgregarUnidadesResponse', Type\ActualizarEnvioAgregarUnidadesResponse::class),
            new ClassMap('ValidarActualizarEnvio', Type\ValidarActualizarEnvio::class),
            new ClassMap('ValidarActualizarEnvioResponse', Type\ValidarActualizarEnvioResponse::class),
            new ClassMap('ValidarActualizarEnvioResult', Type\ValidarActualizarEnvioResult::class),
            new ClassMap('CrearUnidadesEmpaqueBlanco', Type\CrearUnidadesEmpaqueBlanco::class),
            new ClassMap('CrearUnidadesEmpaqueBlancoResponse', Type\CrearUnidadesEmpaqueBlancoResponse::class),
            new ClassMap('CrearUnidadesEmpaqueBlancoResult', Type\CrearUnidadesEmpaqueBlancoResult::class),
            new ClassMap('GenerarGuiaStikerData', Type\GenerarGuiaStikerData::class),
            new ClassMap('ArrayOfLong', Type\ArrayOfLong::class),
            new ClassMap('GenerarGuiaStikerDataResponse', Type\GenerarGuiaStikerDataResponse::class),
            new ClassMap('GenerarGuiaStikerDataResult', Type\GenerarGuiaStikerDataResult::class),
            new ClassMap('GenerarGuiaStikerDataReimpresion', Type\GenerarGuiaStikerDataReimpresion::class),
            new ClassMap('GenerarGuiaStikerDataReimpresionResponse', Type\GenerarGuiaStikerDataReimpresionResponse::class),
            new ClassMap('GenerarGuiaStikerDataReimpresionResult', Type\GenerarGuiaStikerDataReimpresionResult::class),
            new ClassMap('ConsultarGuiaReimpresion', Type\ConsultarGuiaReimpresion::class),
            new ClassMap('ConsultarGuiaReimpresionResponse', Type\ConsultarGuiaReimpresionResponse::class),
            new ClassMap('AnularGuias', Type\AnularGuias::class),
            new ClassMap('ArrayOfResultadoAnulacionGuias', Type\ArrayOfResultadoAnulacionGuias::class),
            new ClassMap('ResultadoAnulacionGuias', Type\ResultadoAnulacionGuias::class),
            new ClassMap('AnularGuiasResponse', Type\AnularGuiasResponse::class),
            new ClassMap('RangoGuias', Type\RangoGuias::class),
            new ClassMap('RangoGuiasResponse', Type\RangoGuiasResponse::class),
            new ClassMap('ArrayOfConsultarGuiasTotalesResultWS', Type\ArrayOfConsultarGuiasTotalesResultWS::class),
            new ClassMap('ConsultarGuiasTotalesResultWS', Type\ConsultarGuiasTotalesResultWS::class),
            new ClassMap('AuthHeader2', Type\AuthHeader2::class),
            new ClassMap('GenerarManifiesto', Type\GenerarManifiesto::class),
            new ClassMap('Lista_Guias_Xml', Type\ListaGuiasXml::class),
            new ClassMap('ArrayOfErrorGeneradoPorGuia', Type\ArrayOfErrorGeneradoPorGuia::class),
            new ClassMap('ErrorGeneradoPorGuia', Type\ErrorGeneradoPorGuia::class),
            new ClassMap('GenerarManifiestoResponse', Type\GenerarManifiestoResponse::class),
            new ClassMap('ConsultarTipoGuias', Type\ConsultarTipoGuias::class),
            new ClassMap('ConsultarTipoGuiasResponse', Type\ConsultarTipoGuiasResponse::class),
            new ClassMap('ArrayOfConsultarTipoGuiasXCodSer', Type\ArrayOfConsultarTipoGuiasXCodSer::class),
            new ClassMap('ConsultarTipoGuiasXCodSer', Type\ConsultarTipoGuiasXCodSer::class),
            new ClassMap('ConsultaRangosGuias', Type\ConsultaRangosGuias::class),
            new ClassMap('ConsultaRangosGuiasResponse', Type\ConsultaRangosGuiasResponse::class),
            new ClassMap('GuiasPendientesXManifestar', Type\GuiasPendientesXManifestar::class),
            new ClassMap('GuiasPendientesXManifestarResponse', Type\GuiasPendientesXManifestarResponse::class),
            new ClassMap('ArrayOfConsultaGuiasXManifestar', Type\ArrayOfConsultaGuiasXManifestar::class),
            new ClassMap('ConsultaGuiasXManifestar', Type\ConsultaGuiasXManifestar::class),
        ]);
    }
}

