parameters:
  cdn_assets_base_url: //s3-o1.retailcrm.tech/eu-central-1/retailcrm-static
  configuration:
    name: Servientrega
    delivery_statuses:
      - code: 1
        name: 'RECIBIDO DEL CLIENTE'
      - code: 2
        name: 'EN PROCESAMIENTO'
      - code: 3
        name: 'ENTREGADO'
      - code: 4
        name: 'ENTREGADO A REMITENTE'
      - code: 5
        name: 'SINIESTRADO'
      - code: 6
        name: 'ENVIO REEXPEDICION'
      - code: 7
        name: 'GUIA GENERADA'
    required_fields:
      - 'phone'
      - 'deliveryAddress.index'
      - 'email'
      - 'length'
      - 'width'
      - 'height'
    plate_list:
      - code: sticker
        label: Sticker
  register:
    secret: '%env(resolve:ONE_STEP_CONNECTION_SECRET)%'
    api-scopes:
      - 'delivery_read'
      - 'delivery_write'
      - 'integration_read'
      - 'integration_write'
