services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  App\Factory\ServientregaSoapClientFactory:
    public: true

  App\Factory\ServientregaRestClientFactory:
    public: true

  App\Factory\RetailcrmClientFactory:
    public: true

  App\Services\TrackingsService:
    public: true

  App\Services\ConnectionService:
    public: true

  App\Services\RegisterService:
    public: true

  App\Dto\Register\RegisterRequest:
    public: true
